package io.sparkadvisor.core.analyze;

import io.sparkadvisor.core.model.Stage;
import io.sparkadvisor.core.util.ValueObjects;
import java.util.Objects;

public final class StageAnalysis {
    private final int stageId,numTasks,failedTaskAttempts,extraTaskAttempts; private final long wallClockMs,maxTaskMs,maxTaskId,medianTaskMs,totalTaskTimeMs,shuffleReadBytes,shuffleWriteBytes,spillBytes,schedulingDelayMs,inputBytes,medianInputBytesPerTask,shuffleFetchWaitMs,shuffleRemoteReadBytes,memorySpillBytes,diskSpillBytes,shuffleReadMedianBytes,shuffleReadMaxBytes,deserializeP95Ms,deserializeSumMs,outputBytes; private final double skewRatio,shuffleSkewRatio,gcRatio;
    public StageAnalysis(int stageId,int numTasks,long wallClockMs,long maxTaskMs,long medianTaskMs,long totalTaskTimeMs,double skewRatio,double shuffleSkewRatio,long shuffleReadBytes,long shuffleWriteBytes,long spillBytes,double gcRatio,long schedulingDelayMs,long inputBytes,long medianInputBytesPerTask){this(stageId,numTasks,wallClockMs,maxTaskMs,-1L,medianTaskMs,totalTaskTimeMs,skewRatio,shuffleSkewRatio,shuffleReadBytes,shuffleWriteBytes,spillBytes,gcRatio,schedulingDelayMs,inputBytes,medianInputBytesPerTask,0L,0L,0,0);}
    public StageAnalysis(int stageId,int numTasks,long wallClockMs,long maxTaskMs,long medianTaskMs,long totalTaskTimeMs,double skewRatio,double shuffleSkewRatio,long shuffleReadBytes,long shuffleWriteBytes,long spillBytes,double gcRatio,long schedulingDelayMs,long inputBytes,long medianInputBytesPerTask,long shuffleFetchWaitMs,long shuffleRemoteReadBytes,int failedTaskAttempts,int extraTaskAttempts){this(stageId,numTasks,wallClockMs,maxTaskMs,-1L,medianTaskMs,totalTaskTimeMs,skewRatio,shuffleSkewRatio,shuffleReadBytes,shuffleWriteBytes,spillBytes,gcRatio,schedulingDelayMs,inputBytes,medianInputBytesPerTask,shuffleFetchWaitMs,shuffleRemoteReadBytes,failedTaskAttempts,extraTaskAttempts);}
    public StageAnalysis(int stageId,int numTasks,long wallClockMs,long maxTaskMs,long maxTaskId,long medianTaskMs,long totalTaskTimeMs,double skewRatio,double shuffleSkewRatio,long shuffleReadBytes,long shuffleWriteBytes,long spillBytes,double gcRatio,long schedulingDelayMs,long inputBytes,long medianInputBytesPerTask,long shuffleFetchWaitMs,long shuffleRemoteReadBytes,int failedTaskAttempts,int extraTaskAttempts){this(stageId,numTasks,wallClockMs,maxTaskMs,maxTaskId,medianTaskMs,totalTaskTimeMs,skewRatio,shuffleSkewRatio,shuffleReadBytes,shuffleWriteBytes,spillBytes,gcRatio,schedulingDelayMs,inputBytes,medianInputBytesPerTask,shuffleFetchWaitMs,shuffleRemoteReadBytes,failedTaskAttempts,extraTaskAttempts,0L,spillBytes,0L,0L,0L,0L,0L);}
    public StageAnalysis(int stageId,int numTasks,long wallClockMs,long maxTaskMs,long maxTaskId,long medianTaskMs,long totalTaskTimeMs,double skewRatio,double shuffleSkewRatio,long shuffleReadBytes,long shuffleWriteBytes,long spillBytes,double gcRatio,long schedulingDelayMs,long inputBytes,long medianInputBytesPerTask,long shuffleFetchWaitMs,long shuffleRemoteReadBytes,int failedTaskAttempts,int extraTaskAttempts,long memorySpillBytes,long diskSpillBytes,long shuffleReadMedianBytes,long shuffleReadMaxBytes,long deserializeP95Ms,long deserializeSumMs,long outputBytes){this.stageId=stageId;this.numTasks=numTasks;this.wallClockMs=wallClockMs;this.maxTaskMs=maxTaskMs;this.maxTaskId=maxTaskId;this.medianTaskMs=medianTaskMs;this.totalTaskTimeMs=totalTaskTimeMs;this.skewRatio=skewRatio;this.shuffleSkewRatio=shuffleSkewRatio;this.shuffleReadBytes=shuffleReadBytes;this.shuffleWriteBytes=shuffleWriteBytes;this.spillBytes=spillBytes;this.gcRatio=gcRatio;this.schedulingDelayMs=schedulingDelayMs;this.inputBytes=inputBytes;this.medianInputBytesPerTask=medianInputBytesPerTask;this.shuffleFetchWaitMs=shuffleFetchWaitMs;this.shuffleRemoteReadBytes=shuffleRemoteReadBytes;this.failedTaskAttempts=failedTaskAttempts;this.extraTaskAttempts=extraTaskAttempts;this.memorySpillBytes=memorySpillBytes;this.diskSpillBytes=diskSpillBytes;this.shuffleReadMedianBytes=shuffleReadMedianBytes;this.shuffleReadMaxBytes=shuffleReadMaxBytes;this.deserializeP95Ms=deserializeP95Ms;this.deserializeSumMs=deserializeSumMs;this.outputBytes=outputBytes;}
    public int stageId(){return stageId;} public int numTasks(){return numTasks;} public long wallClockMs(){return wallClockMs;} public long maxTaskMs(){return maxTaskMs;} public long maxTaskId(){return maxTaskId;} public long medianTaskMs(){return medianTaskMs;} public long totalTaskTimeMs(){return totalTaskTimeMs;} public double skewRatio(){return skewRatio;} public double shuffleSkewRatio(){return shuffleSkewRatio;} public long shuffleReadBytes(){return shuffleReadBytes;} public long shuffleWriteBytes(){return shuffleWriteBytes;} public long spillBytes(){return spillBytes;} public long memorySpillBytes(){return memorySpillBytes;} public long diskSpillBytes(){return diskSpillBytes;} public long shuffleReadMedianBytes(){return shuffleReadMedianBytes;} public long shuffleReadMaxBytes(){return shuffleReadMaxBytes;} public long deserializeP95Ms(){return deserializeP95Ms;} public long deserializeSumMs(){return deserializeSumMs;} public long outputBytes(){return outputBytes;} public double gcRatio(){return gcRatio;} public long schedulingDelayMs(){return schedulingDelayMs;} public long inputBytes(){return inputBytes;} public long medianInputBytesPerTask(){return medianInputBytesPerTask;} public long shuffleFetchWaitMs(){return shuffleFetchWaitMs;} public long shuffleRemoteReadBytes(){return shuffleRemoteReadBytes;} public int failedTaskAttempts(){return failedTaskAttempts;} public int extraTaskAttempts(){return extraTaskAttempts;}
    public static StageAnalysis from(Stage s){io.sparkadvisor.core.metrics.Distribution dur=s.taskStats().durationMs(),sr=s.taskStats().shuffleReadBytes(),in=s.taskStats().inputBytes(),deser=s.taskStats().deserializeMs(); long totalTaskMs=dur.sum(); long gcSum=s.taskStats().gcTimeMs().sum(); double gcRatio=totalTaskMs==0?0.0:(double)gcSum/(double)totalTaskMs; return new StageAnalysis(s.stageId(),s.numTasks(),s.wallClockMs(),dur.max(),s.maxTaskId(),dur.median(),totalTaskMs,dur.skewRatio(),sr.skewRatio(),s.shuffleReadTotalBytes(),s.shuffleWriteTotalBytes(),s.taskStats().totalSpillBytes(),gcRatio,s.schedulingDelayMs(),in.sum(),in.median(),s.shuffleFetchWaitMs(),s.shuffleRemoteReadBytes(),s.failedTaskAttempts(),s.extraTaskAttempts(),s.taskStats().memorySpillBytes().sum(),s.taskStats().diskSpillBytes().sum(),sr.median(),sr.max(),deser.p95(),deser.sum(),s.taskStats().outputBytes().sum());}
    @Override public boolean equals(Object o){if(this==o)return true; if(!(o instanceof StageAnalysis))return false; StageAnalysis a=(StageAnalysis)o; return stageId==a.stageId&&numTasks==a.numTasks&&wallClockMs==a.wallClockMs&&maxTaskMs==a.maxTaskMs&&maxTaskId==a.maxTaskId&&medianTaskMs==a.medianTaskMs&&totalTaskTimeMs==a.totalTaskTimeMs&&Double.compare(a.skewRatio,skewRatio)==0&&Double.compare(a.shuffleSkewRatio,shuffleSkewRatio)==0&&shuffleReadBytes==a.shuffleReadBytes&&shuffleWriteBytes==a.shuffleWriteBytes&&spillBytes==a.spillBytes&&memorySpillBytes==a.memorySpillBytes&&diskSpillBytes==a.diskSpillBytes&&shuffleReadMedianBytes==a.shuffleReadMedianBytes&&shuffleReadMaxBytes==a.shuffleReadMaxBytes&&deserializeP95Ms==a.deserializeP95Ms&&deserializeSumMs==a.deserializeSumMs&&outputBytes==a.outputBytes&&Double.compare(a.gcRatio,gcRatio)==0&&schedulingDelayMs==a.schedulingDelayMs&&inputBytes==a.inputBytes&&medianInputBytesPerTask==a.medianInputBytesPerTask&&shuffleFetchWaitMs==a.shuffleFetchWaitMs&&shuffleRemoteReadBytes==a.shuffleRemoteReadBytes&&failedTaskAttempts==a.failedTaskAttempts&&extraTaskAttempts==a.extraTaskAttempts;}
    @Override public int hashCode(){return Objects.hash(stageId,numTasks,wallClockMs,maxTaskMs,maxTaskId,medianTaskMs,totalTaskTimeMs,skewRatio,shuffleSkewRatio,shuffleReadBytes,shuffleWriteBytes,spillBytes,memorySpillBytes,diskSpillBytes,shuffleReadMedianBytes,shuffleReadMaxBytes,deserializeP95Ms,deserializeSumMs,outputBytes,gcRatio,schedulingDelayMs,inputBytes,medianInputBytesPerTask,shuffleFetchWaitMs,shuffleRemoteReadBytes,failedTaskAttempts,extraTaskAttempts);}
    @Override public String toString(){return ValueObjects.toString(this);} }
